---

###############
#   Preq
###############

- name: Create directoryies
  file:
    state: directory
    path: "{{ httpd_dir_vhosts }}/{{ vhost.domainname }}/{{ item.dir }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '0750'
    recurse: yes
  with_items: "{{ httpd_vhost_dirs }}"

- name: Create httpd config
  template:
    src: "templates/httpd.conf.j2"
    dest: "{{ httpd_dir_vhosts }}/{{ vhost.domainname }}/config/httpd.conf"
    owner: root
    group: root
    mode: '0640'
  notify: httpd restarted

- name: Create nginx config
  template:
    src: "templates/httpd.conf.j2"
    dest: "{{ httpd_dir_vhosts }}/{{ vhost.domainname }}/config/nginx.conf"
    owner: root
    group: root
    mode: '0640'
  notify: nginx restarted
...
